// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANITPNlBCSmzSK_dRTm4nMTTYhHh9GVUM',
    appId: '1:641940396709:web:f8f0a8d4db719778cecb4c',
    messagingSenderId: '641940396709',
    projectId: 'login-signup-88438',
    authDomain: 'login-signup-88438.firebaseapp.com',
    storageBucket: 'login-signup-88438.appspot.com',
    measurementId: 'G-9DWE90SSSK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxb6-KgmOxRfuj4wmyLR3VJd7YjGxtkSk',
    appId: '1:641940396709:android:08a3864e5e570d18cecb4c',
    messagingSenderId: '641940396709',
    projectId: 'login-signup-88438',
    storageBucket: 'login-signup-88438.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzu-AsCT8efC01gSAMijSU2-Qkjne3mJo',
    appId: '1:641940396709:ios:7c86216e8e33882dcecb4c',
    messagingSenderId: '641940396709',
    projectId: 'login-signup-88438',
    storageBucket: 'login-signup-88438.appspot.com',
    iosBundleId: 'com.example.loginSignupFirebase',
  );

}